1.1

In [6]:
import random

# Создаем список из 100 элементов и округляем их до сотых
numbers = [round(random.uniform(0, 100), 2) for _ in range(100)]

# Заменяем все числа меньше 10 на 10
numbers = [10 if num < 10 else num for num in numbers]

# Заменяем все числа больше 90 на 90
numbers = [90 if num > 90 else num for num in numbers]

# Находим среднее значение, минимум и максимум
average = sum(numbers) / len(numbers)
minimum = min(numbers)
maximum = max(numbers)

# Выводим результаты
print(f"Среднее значение: {average:.2f}")
print(f"Минимум: {minimum:.2f}")
print(f"Максимум: {maximum:.2f}")

Среднее значение: 48.59
Минимум: 10.00
Максимум: 90.00


1.2


In [7]:
import numpy as np

In [9]:
m = int(input('m: '))
n = int(input('n: '))

# Создаем матрицу m x n
matrix = np.zeros((m, n))

# Заполняем ячейки по условию
for i in range(m):
    for j in range(n):
        matrix[i, j] = min(i + 1, m - i, j + 1, n - j)

# Выводим полученную матрицу
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 2. 2. 2. 2. 2. 1.]
 [1. 2. 3. 3. 3. 3. 3. 3. 2. 1.]
 [1. 2. 3. 4. 4. 4. 4. 3. 2. 1.]
 [1. 2. 3. 4. 5. 5. 4. 3. 2. 1.]
 [1. 2. 3. 4. 5. 5. 4. 3. 2. 1.]
 [1. 2. 3. 4. 4. 4. 4. 3. 2. 1.]
 [1. 2. 3. 3. 3. 3. 3. 3. 2. 1.]
 [1. 2. 2. 2. 2. 2. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


1.3


In [14]:
# Создаем два массива по 30 случайных чисел
array1 = np.random.uniform(15, 33, 30)
array2 = np.random.uniform(15, 33, 30)

# Объединяем массивы в один
combined_array = np.concatenate((array1, array2))

# Фильтруем значения, которые больше 24
filtered_array = combined_array[combined_array > 24]

# Находим количество элементов в итоговом массиве
count = len(filtered_array)

# Находим среднее значение
average = np.mean(filtered_array)

# Находим максимальный и минимальный элементы
maximum = np.max(filtered_array)
minimum = np.min(filtered_array)

# Находим среднеквадратичное отклонение
std = np.sqrt(np.mean(np.square(filtered_array - average)))

# Выводим результаты
print(f"Количество элементов: {count}")
print(f"Среднее значение: {average:.2f}")
print(f"Максимальный элемент: {maximum:.2f}")
print(f"Минимальный элемент: {minimum:.2f}")
print(f"Среднеквадратичное отклонение: {std:.2f}")

Количество элементов: 32
Среднее значение: 28.30
Максимальный элемент: 32.01
Минимальный элемент: 24.16
Среднеквадратичное отклонение: 2.57


1.4

In [15]:
import cv2
import numpy as np

In [16]:
def copy_image(path: str, yuv_change: list, hsv_change: list):

    # Загружаем изображение
    img = cv2.imread(path)

    # Проверяем, что изображение не менее 1000x800 пикселей
    if img.shape[0] < 1000 or img.shape[1] < 800:
        print("Изображение должно быть не менее 1000x800 пикселей.")
        return

    # Конвертирование изображения в YUV и HSV
    yuv_img = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) # Hue, Saturation, Value

    # Изменяем значения Y, U, V в YUV
    yuv_img[:, :] = yuv_change
    
    # Изменяем значения H, S, V в HSV
    hsv_img[:, :] = hsv_change

    # Преобразуем обратно в BGR
    yuv_bgr_img = cv2.cvtColor(yuv_img, cv2.COLOR_YUV2BGR)
    hsv_bgr_img = cv2.cvtColor(hsv_img, cv2.COLOR_HSV2BGR)

    # Выводим изображения
    cv2.imshow('Original', img)
    cv2.imshow('YUV', yuv_bgr_img)
    cv2.imshow('HSV', hsv_bgr_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [17]:
yuv_change = [100, 100, 150]
hsv_change = [100, 100, 150]

copy_image('./cat.jpg', yuv_change, hsv_change)